<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.8.50" />

    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />

    <PackageVersion Include="Terminal.Gui" Version="1.17.1" />

    <PackageVersion Include="Avalonia" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Android" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Sqlite" Version="11.2.3" />
  </ItemGroup>

</Project>
